export const homeObjOne = {
    id: "about",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Roller Derby",
    headLine: "if you cant nice play roller derby",
    description: "Derby love",
    buttonLabel: "Get started",
    imgStart: true,
    img: require('../../images/img.jpg'),
    alt: 'wasabi',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: "discover",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Roller Derby",
    headLine: "if you cant nice play roller derby",
    description: "Derby love",
    buttonLabel: "Get started",
    imgStart: false,
    img: require('../../images/img.jpg'),
    alt: 'wasabi',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: "signup",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Roller Derby",
    headLine: "if you cant nice play roller derby",
    description: "Derby love",
    buttonLabel: "Get started",
    imgStart: true,
    img: require('../../images/img.jpg'),
    alt: 'wasabi',
    dark: true,
    primary: true,
    darkText: false,
};