export const homeObjOne = {
    id: "about",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "What is Roller Derby?",
    headLine: "if you cant nice play roller derby",
    description: "Derby love",
    buttonLabel: "About Derby",
    imgStart: true,
    img: require('../../../images/img.jpg'),
    alt: 'about',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: "league",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Roller Derby League",
    headLine: "Search a league near you.",
    description: "Follow the link to join your desire league.",
    buttonLabel: "Get started",
    to: require('../../Leagues/index'),
    imgStart: false,
    img: require('../../../images/img2.jpg'),
    alt: 'league',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: "scoreboard",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Scoreboard",
    headLine: "Results for SCRIM",
    description: "Check the latest results from SCRIM.",
    buttonLabel: "Check",
    imgStart: true,
    img: require('../../../images/scoreboard.jpg'),
    alt: 'score',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjFour = {
    id: "signup",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Sign Up",
    headLine: "Sign up now",
    description: "Register now to receive latest newsletter",
    buttonLabel: "Join",
    to: "/register",
    imgStart: false,
    img: require('../../../images/img1.jpg'),
    alt: 'join',
    dark: false,
    primary: false,
    darkText: true,
};