export const homeObjOne = {
    id: "about",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "What is Roller Derby?",
    headLine: "It's like playing speed chess while bricks are thrown at you!",
    description: "Roller Derby was born on Aug 13, 1935, at the Chicago Coliseum, United States",
    buttonLabel: "EXPLORE",
    imgStart: true,
    img: require('../../../images/img.jpg'),
    alt: 'about',
    dark: true,
    primary: true,
    darkText: true,
};

export const homeObjTwo = {
    id: "league",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Roller Derby League",
    headLine: "If you can't play nice, play roller derby.",
    description: "Find a roller derby league near you.",
    buttonLabel: "SEARCH",
    imgStart: false,
    img: require('../../../images/img2.jpg'),
    alt: 'league',
    dark: false,
    primary: false,
    darkText: false,
};

export const homeObjThree = {
    id: "scoreboard",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Scoreboard",
    headLine: "BOUT (official game) & SCRIM (gameplay practice)",
    description: "Check the score online 24/7!",
    buttonLabel: "CHECK",
    imgStart: true,
    img: require('../../../images/scoreboard.jpg'),
    alt: 'score',
    dark: true,
    primary: true,
    darkText: true,
};

export const homeObjFour = {
    id: "signup",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Create an account",
    headLine: "Just get in there, find what you are good at and do it!",
    description: "Devotion-Friendship-Passion-Respect",
    buttonLabel: "JOIN",
    imgStart: false,
    img: require('../../../images/img1.jpg'),
    alt: require('../../../pages/SignupPage'),
    dark: false,
    primary: false,
    darkText: false,
};